export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Command", icon: "terminal", color: "#10b981", isSystem: true },
  { id: "type_note", name: "Note", icon: "file-text", color: "#f59e0b", isSystem: true },
  { id: "type_file", name: "File", icon: "file", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "image", color: "#ec4899", isSystem: true },
  { id: "type_url", name: "URL", icon: "link", color: "#14b8a6", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    createdAt: "2026-01-08T00:00:00Z",
    updatedAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-01-14T00:00:00Z",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    createdAt: "2025-12-20T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-01-08T00:00:00Z",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-13T00:00:00Z",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "text",
    content: `import { useState, useEffect } from 'react';\n\nexport function useAuth() {\n  const [user, setUser] = useState(null);\n  // ...\n}`,
    description: "Custom authentication hook for React applications",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["react", "auth", "hooks"],
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "text",
    content: `async function fetchWithRetry(url, retries = 3) {\n  // exponential backoff retry logic\n}`,
    description: "Fetch wrapper with exponential backoff retry logic",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    typeId: "type_snippet",
    collectionId: "col_1",
    tags: ["api", "error-handling", "fetch"],
    createdAt: "2026-01-12T00:00:00Z",
    updatedAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "item_3",
    title: "Git Undo Last Commit",
    contentType: "text",
    content: "git reset --soft HEAD~1",
    description: "Undo the last commit while keeping changes staged",
    isFavorite: true,
    isPinned: false,
    language: null,
    typeId: "type_command",
    collectionId: "col_5",
    tags: ["git", "undo"],
    createdAt: "2026-01-08T00:00:00Z",
    updatedAt: "2026-01-08T00:00:00Z",
  },
  {
    id: "item_4",
    title: "Code Review Prompt",
    contentType: "text",
    content: "Review this code for security vulnerabilities, performance issues, and adherence to best practices. Provide specific, actionable feedback.",
    description: "General-purpose code review AI prompt",
    isFavorite: true,
    isPinned: false,
    language: null,
    typeId: "type_prompt",
    collectionId: "col_6",
    tags: ["code-review", "ai", "prompt"],
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "item_5",
    title: "Python List Comprehension Patterns",
    contentType: "text",
    content: "# Filter and transform\nresult = [f(x) for x in items if condition(x)]",
    description: "Common Python list comprehension examples",
    isFavorite: false,
    isPinned: false,
    language: "python",
    typeId: "type_snippet",
    collectionId: "col_2",
    tags: ["python", "list", "comprehension"],
    createdAt: "2026-01-11T00:00:00Z",
    updatedAt: "2026-01-11T00:00:00Z",
  },
  {
    id: "item_6",
    title: "Next.js App Router Notes",
    contentType: "text",
    content: "Server components render on the server by default. Use 'use client' only when needed for interactivity.",
    description: "Key notes on Next.js App Router conventions",
    isFavorite: false,
    isPinned: false,
    language: null,
    typeId: "type_note",
    collectionId: null,
    tags: ["nextjs", "react", "app-router"],
    createdAt: "2026-01-13T00:00:00Z",
    updatedAt: "2026-01-13T00:00:00Z",
  },
];

export const mockTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 18,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 3,
  type_url: 8,
};
